In [2]:
from tensorflow.keras.models import load_model

new_model = load_model('./model/second.h5')

In [10]:
labels = ['transistor-good', 'capsule-good', 'wood-good', 'bottle-good',
       'screw-good', 'cable-bent_wire', 'carpet-hole', 'hazelnut-good',
       'pill-pill_type', 'cable-good', 'metal_nut-scratch', 'pill-good',
       'screw-thread_side', 'zipper-fabric_border', 'leather-good',
       'pill-scratch', 'toothbrush-good', 'hazelnut-crack',
       'screw-manipulated_front', 'zipper-good', 'tile-good',
       'carpet-good', 'metal_nut-good', 'bottle-contamination',
       'grid-good', 'zipper-split_teeth', 'pill-crack', 'wood-combined',
       'pill-color', 'screw-thread_top', 'cable-missing_cable',
       'capsule-squeeze', 'zipper-rough', 'capsule-crack', 'capsule-poke',
       'metal_nut-flip', 'carpet-metal_contamination', 'metal_nut-color',
       'transistor-bent_lead', 'zipper-fabric_interior', 'leather-fold',
       'tile-glue_strip', 'screw-scratch_neck', 'screw-scratch_head',
       'hazelnut-cut', 'bottle-broken_large', 'bottle-broken_small',
       'leather-cut', 'cable-cut_outer_insulation',
       'zipper-squeezed_teeth', 'toothbrush-defective',
       'cable-cut_inner_insulation', 'pill-contamination',
       'cable-missing_wire', 'carpet-thread', 'grid-broken',
       'pill-faulty_imprint', 'hazelnut-hole', 'leather-glue',
       'leather-poke', 'transistor-damaged_case', 'wood-scratch',
       'tile-gray_stroke', 'capsule-faulty_imprint', 'grid-glue',
       'zipper-combined', 'carpet-color', 'grid-bent', 'pill-combined',
       'hazelnut-print', 'cable-combined', 'capsule-scratch',
       'metal_nut-bent', 'zipper-broken_teeth', 'tile-oil',
       'transistor-misplaced', 'grid-thread', 'grid-metal_contamination',
       'carpet-cut', 'wood-color', 'cable-cable_swap', 'tile-crack',
       'leather-color', 'cable-poke_insulation', 'transistor-cut_lead',
       'wood-hole', 'tile-rough', 'wood-liquid']

In [45]:
from PIL import Image
import numpy as np

image = Image.open('./data/test/20012.png')
image = image.resize((256,256))
image = np.array(image)
x_test = np.array([image])
x_test = (x_test)/255

y_predict = new_model.predict(x_test)

label = labels[y_predict[0].argmax()]
confidence = y_predict[0][y_predict[0].argmax()]
print(label, confidence) #

ValueError: in user code:

    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\training.py:1462 predict_function  *
        return step_function(self, iterator)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\training.py:1452 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\training.py:1445 run_step  **
        outputs = model.predict_step(data)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\training.py:1418 predict_step
        return self(x, training=False)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:191 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_5 is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: [None, 256, 256]


In [18]:
import pandas as pd
import os
import matplotlib.pyplot as plt

submission_df = pd.read_csv('./data/sample_submission.csv', index_col='index')
test_df = pd.read_csv('./data/test_df.csv', index_col='index')

dir_path = './data/test'

In [36]:
submission_df

label
index           
0      tile-good
1      tile-good
2      tile-good
3      tile-good
4      tile-good
...          ...
2149   tile-good
2150   tile-good
2151   tile-good
2152   tile-good
2153   tile-good

[2154 rows x 1 columns]

In [46]:
i = 0
for num, f_name, label in zip(range(len(test_df)) ,test_df['file_name'], submission_df['label']):
#     print(num, f_name, label)
    image_path = os.path.join(dir_path, f_name)
    image_path = image_path.replace('\\','/')
    image = Image.open(image_path)
    image = image.resize((256,256))
    image = np.array(image)
    x_test = np.array([image])
    x_test = (x_test)/255
    print(x_test)
    y_predict = new_model.predict(x_test)
    label = labels[y_predict[0].argmax()]
    submission_df.iloc[num]['label'] = label
    print(num, f_name, label)

display(submission_df)

[[[[0.59607843 0.60784314 0.56078431]
   [0.58823529 0.61568627 0.56470588]
   [0.55294118 0.59215686 0.54509804]
   ...
   [0.5372549  0.53333333 0.50980392]
   [0.55294118 0.52941176 0.52156863]
   [0.59215686 0.59215686 0.56862745]]

  [[0.59607843 0.61960784 0.56862745]
   [0.54509804 0.57647059 0.5372549 ]
   [0.4627451  0.47843137 0.44313725]
   ...
   [0.51372549 0.50588235 0.47843137]
   [0.4627451  0.44705882 0.41568627]
   [0.45098039 0.43921569 0.40784314]]

  [[0.54117647 0.55686275 0.5254902 ]
   [0.44705882 0.44313725 0.41568627]
   [0.3254902  0.32156863 0.30196078]
   ...
   [0.55294118 0.54117647 0.51372549]
   [0.44705882 0.43921569 0.41176471]
   [0.36470588 0.34509804 0.32156863]]

  ...

  [[0.33333333 0.32941176 0.29803922]
   [0.30588235 0.30196078 0.27058824]
   [0.27058824 0.2745098  0.25490196]
   ...
   [0.44705882 0.42745098 0.43529412]
   [0.58431373 0.59215686 0.58039216]
   [0.61568627 0.61176471 0.59215686]]

  [[0.36078431 0.37254902 0.34509804]
   [0.3

[[[[0.34901961 0.22745098 0.19607843]
   [0.38039216 0.25098039 0.21568627]
   [0.38039216 0.25490196 0.21960784]
   ...
   [0.34901961 0.21960784 0.19215686]
   [0.38823529 0.24313725 0.20392157]
   [0.36470588 0.23921569 0.20392157]]

  [[0.30196078 0.2        0.17647059]
   [0.34509804 0.23529412 0.20392157]
   [0.38431373 0.25490196 0.21568627]
   ...
   [0.33333333 0.21176471 0.18431373]
   [0.34117647 0.20784314 0.17647059]
   [0.36078431 0.23137255 0.19607843]]

  [[0.36470588 0.24705882 0.21176471]
   [0.40392157 0.26666667 0.22352941]
   [0.38039216 0.24705882 0.20392157]
   ...
   [0.37254902 0.24705882 0.20784314]
   [0.37647059 0.24705882 0.21176471]
   [0.38431373 0.25098039 0.21568627]]

  ...

  [[0.26666667 0.18039216 0.16078431]
   [0.31372549 0.21568627 0.18823529]
   [0.38823529 0.25882353 0.22745098]
   ...
   [0.29411765 0.19215686 0.17254902]
   [0.29411765 0.19215686 0.16078431]
   [0.3372549  0.21176471 0.18039216]]

  [[0.28235294 0.18823529 0.16470588]
   [0.2

ValueError: in user code:

    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\training.py:1462 predict_function  *
        return step_function(self, iterator)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\training.py:1452 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\training.py:1445 run_step  **
        outputs = model.predict_step(data)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\training.py:1418 predict_step
        return self(x, training=False)
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    C:\Users\Lenovo\anaconda3\envs\machine_TF2\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:191 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_5 is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: [None, 256, 256]
